### PR TITLE
use pouchdb-promise

### PR DESCRIPTION
**Pull request by garrensmith**
Use pouchdb-promise instead of using lie directly

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks!

**Comment by garrensmith** [comment]
Nolan, could you publish a new version of this? Then we can fix
pouchdb-find.

**Comment by nolanlawson** [comment]
Already on it!  
  
\---

Nolan Lawson

https://nolanlawson.com

https://github.com/nolanlawson

  

On Jun 14 2016, at 6:49 am, garren smith &lt;notifications@github.com&gt;
wrote:  

> Nolan, could you publish a new version of this? Then we can fix  
>  pouchdb-find.  
>  
>  On Tue, Jun 14, 2016 at 3:48 PM, Nolan Lawson
&lt;notifications@github.com&gt;  
>  wrote:  
>  
>  &gt; Merged #20 &lt;https://github.com/pouchdb/upsert/pull/20&gt;.  
>  &gt;  
>  &gt; —  
>  &gt; You are receiving this because you authored the thread.  
>  &gt; Reply to this email directly, view it on GitHub  
>  &gt; &lt;https://github.com/pouchdb/upsert/pull/20#event-691847883&gt;, or
mute the  
>  &gt; thread  
>  &gt;
&lt;https://github.com/notifications/unsubscribe/AAK9Anc1HCeA7qR1WwpdD9pq2cbBtUrtks5qLrFLgaJpZM4I0TXg&gt;  
>  &gt; .  
>  &gt;  
>

>

> —  
> You are receiving this because you modified the open/close state.  
> Reply to this email directly, [view it on
GitHub](https://github.com/pouchdb/upsert/pull/20#issuecomment-225886609), or
[mute the thread](https://github.com/notifications/unsubscribe
/AARUwiHs_4__816ofj0tUntAu-
oHr4L0ks5qLrGAgaJpZM4I0TXg).

**Comment by nolanlawson** [comment]
Done, 2.0.1.

**Pull request merged**
