### PR TITLE
add: expose self as pouchdbUpsert and bind to self

### PR DESCRIPTION
**Pull request by zhuangya**
so we can use this lib in webworks =)

ref nolanlawson/pouchdb-find#200

### CODE REVIEW

**Comment by nolanlawson** [comment]
See my comment in https://github.com/nolanlawson/pouchdb-find/pull/200#issuecomment-229388923 ; we could definitely try to detect all global usages of PouchDB in every possible env, but I try to avoid doing so because it's a slippery slope, thanks for understanding. :)

**Comment by zhuangya** [comment]
well, if do not generate/pack the script in "standalone" mode, there is no way to `importScripts` and apply it to `PouchDB` as far as i can see.
i fully understand your concertn, but maybe browserify the script in standalone with with `-s pouchdbUpsert` ?

**Comment by nolanlawson** [comment]
Yes, just browserify and insert into your worker, that's what I would do. TBH we should have made our own bundle a standalone UMD bundle, and the fact that we didn't is a bug. I'll fix that.

**Comment by nolanlawson** [comment]
fixed in 2.0.2 now

**Pull request closed without merging**
