### PR TITLE
Upsert results now returns the id, bower main file cannot be minified

### PR DESCRIPTION
**Pull request by AndreaGi**

### CODE REVIEW

**Comment by nolanlawson** [comment]
The Bower main issue is unrelated, but the `id` fix looks fine to me. I don't see any reason why it shouldn't return the `id` in the results.

The PhantomJS error in Travis seems spurious; I've restarted it so hopefully it'll pass.

**Comment by nolanlawson** [comment]
Could you please also update the documentation to note that the `id` is returned along with `rev` and `updated`?

**Comment by AndreaGi** [comment]
I've updated the document. The test on Travis are failing, but they pass on my local machine, although looks like 'test-browser' never worked correctly and gave a false positive on the last two builds:
https://travis-ci.org/pouchdb/upsert/jobs/141513121
https://travis-ci.org/pouchdb/upsert/jobs/141513540

**Comment by nolanlawson** [comment]
If the `test-browser` failure is unrelated then we should open a separate issue/fix for that. I'm testing here:  #32

**Comment by nolanlawson** [comment]
Sorry, we have to clean house and figure out why master is broken. :confused: Once that's done then I'll be happy to merge this PR.

**Comment by nolanlawson** [comment]
merged as f9c4f71e202474d84bfdd61bae27f80b77e8e25c and 2e91cb641b01b3564056222e6d208b0a1d9fa667, thanks! You are now a collaborator on this project. :)

**Comment by jordancardwell** [comment]
Thanks @nolanlawson @AndreaGi 👍

**Pull request closed without merging**
